CREATE TABLE PROVENANCE_LEDGER (
    RUN_ID VARCHAR PRIMARY KEY,
    OPERATION VARCHAR,
    TIMESTAMP TIMESTAMP,
    HASH_P VARCHAR
);

CREATE TABLE TAXON_RECONCILE (
    ENTITY_UUID UUID PRIMARY KEY,
    RUN_ID VARCHAR,
    RAW_LABEL VARCHAR,
    CANONICAL_NAME VARCHAR,
    CONFIDENCE_SCORE DOUBLE,
    MATCH_TYPE VARCHAR
);

CREATE INDEX idx_provenance_run_id ON PROVENANCE_LEDGER(RUN_ID);
CREATE INDEX idx_reconcile_run_id ON TAXON_RECONCILE(RUN_ID);
